apiVersion: v1
data:
  text: {{ required "Argument --set eveAppClientId='<eve-app-client-id>' is required." .Values.eveAppClientId | b64enc }}
kind: Secret
metadata:
  annotations:
    "jenkins.io/credentials-description": "Eve Developers application client ID"
  labels:
    "jenkins.io/credentials-type": "secretText"
  name: eve-app-client-id
type: Opaque
