apiVersion: v1
data:
  text: {{ required "Argument --set eveAppClientSecret='<eve-app-client-secret>' is required." .Values.eveAppClientSecret | b64enc }}
kind: Secret
metadata:
  annotations:
    "jenkins.io/credentials-description": "Eve Developers application client secret"
  labels:
    "jenkins.io/credentials-type": "secretText"
  name: eve-app-client-secret
type: Opaque
