apiVersion: v1
data:
  text: {{ required "Argument --set mongoInitdbRootPassword='<mongo-initdb-root-password>' is required." .Values.mongoInitdbRootPassword | b64enc }}
kind: Secret
metadata:
  annotations:
    "jenkins.io/credentials-description": "Password with which to initialize MongoDB root user"
  labels:
    "jenkins.io/credentials-type": "secretText"
  name: mongo-initdb-root-password
type: Opaque
