apiVersion: v1
data:
  text: {{ required "Argument --set githubToken='<github-token>' is required." .Values.githubToken | b64enc }}
kind: Secret
metadata:
  annotations:
    "jenkins.io/credentials-description": "GitHub personal access token"
  labels:
    "jenkins.io/credentials-type": "secretText"
  name: github-token
type: Opaque
