apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jenkins
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: {{ required "Argument --set host='<host>' is required." .Values.host }}
      http:
        paths:
          - path: {{ required "Argument --set jenkins.controller.jenkinsUriPrefix='<jenkins-uri-prefix'> is required." .Values.jenkins.controller.jenkinsUriPrefix }}
            backend:
              serviceName: jenkins
              servicePort: 8080
