apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: jenkins-admin-password
data:
  adminPassword: {{ required "Argument --set jenkins.controller.adminPassword='<admin-password>' is required." .Values.jenkins.controller.adminPassword | b64enc }}
