jenkins:
  controller:
    imagePullPolicy: IfNotPresent
    installPlugins:
      # Default plugins for this helm chart version
      - kubernetes:1.29.4
      - workflow-aggregator:2.6
      - git:4.7.1
      - configuration-as-code:1.51

      # Additional plugins
      - blueocean:1.24.7  # Includes GitHub plugin
      - cobertura:1.16
      - embeddable-build-status:2.0.3
      - job-dsl:1.77
      - kubernetes-credentials-provider:0.20
      - theme-manager:0.6

    JCasC:
      authorizationStrategy: |-
        loggedInUsersCanDoAnything:
          allowAnonymousRead: true
      configScripts:
        job-settings: |
          jobs:
            - script: >
                multibranchPipelineJob('api') {
                  description 'Web endpoints and business logic'
                  branchSources {
                    branchSource {
                      source {
                        github {
                          apiUri 'https://api.github.com'
                          configuredByUrl true
                          credentialsId 'github-username-and-token'
                          id 'main'
                          repoOwner 'iskprinter'
                          repository 'api'
                          repositoryUrl 'https://github.com/iskprinter/api.git'
                          traits {
                            gitHubBranchDiscovery {
                              strategyId 3
                            }
                            gitHubPullRequestDiscovery {
                              strategyId 1
                            }
                            headRegexFilter {
                              regex '^main$|^PR-\\d+$'
                            }
                            localBranchTrait()
                          }
                        }
                      }
                    }
                  }
                  factory {
                    workflowBranchProjectFactory {
                      scriptPath 'Jenkinsfile'
                    }
                  }
                }
            - script: >
                multibranchPipelineJob('helm') {
                  description 'Helm chart for all application components'
                  branchSources {
                    branchSource {
                      source {
                        github {
                          apiUri 'https://api.github.com'
                          configuredByUrl true
                          credentialsId 'github-username-and-token'
                          id 'main'
                          repoOwner 'iskprinter'
                          repository 'helm'
                          repositoryUrl 'https://github.com/iskprinter/helm.git'
                          traits {
                            gitHubBranchDiscovery {
                              strategyId 3
                            }
                            gitHubPullRequestDiscovery {
                              strategyId 1
                            }
                            headRegexFilter {
                              regex '^main$|^PR-\\d+$'
                            }
                            localBranchTrait()
                          }
                        }
                      }
                    }
                  }
                  factory {
                    workflowBranchProjectFactory {
                      scriptPath 'Jenkinsfile'
                    }
                  }
                }
            - script: >
                multibranchPipelineJob('frontend') {
                  description 'Browser client'
                  branchSources {
                    branchSource {
                      source {
                        github {
                          apiUri 'https://api.github.com'
                          configuredByUrl true
                          credentialsId 'github-username-and-token'
                          id 'main'
                          repoOwner 'iskprinter'
                          repository 'frontend'
                          repositoryUrl 'https://github.com/iskprinter/frontend.git'
                          traits {
                            gitHubBranchDiscovery {
                              strategyId 3
                            }
                            gitHubPullRequestDiscovery {
                              strategyId 1
                            }
                            headRegexFilter {
                              regex '^main$|^PR-\\d+$'
                            }
                            localBranchTrait()
                          }
                        }
                      }
                    }
                  }
                  factory {
                    workflowBranchProjectFactory {
                      scriptPath 'Jenkinsfile'
                    }
                  }
                }
            - script: >
                multibranchPipelineJob('weekly-download') {
                  description 'A weekly sync of low-frequency eve online data'
                  branchSources {
                    branchSource {
                      source {
                        github {
                          apiUri 'https://api.github.com'
                          configuredByUrl true
                          credentialsId 'github-username-and-token'
                          id 'main'
                          repoOwner 'iskprinter'
                          repository 'weekly-download'
                          repositoryUrl 'https://github.com/iskprinter/weekly-download.git'
                          traits {
                            gitHubBranchDiscovery {
                              strategyId 3
                            }
                            gitHubPullRequestDiscovery {
                              strategyId 1
                            }
                            headRegexFilter {
                              regex '^main$|^PR-\\d+$'
                            }
                            localBranchTrait()
                          }
                        }
                      }
                    }
                  }
                  factory {
                    workflowBranchProjectFactory {
                      scriptPath 'Jenkinsfile'
                    }
                  }
                }
        unclassified-settings: |
          unclassified:
            gitHubPluginConfig:
              configs:
              - credentialsId: "github-token"
                name: "GitHub"
              hookUrl: https://iskprinter.com/jenkins/github-webhook/
            themeManager:
              disableUserThemes: true
              theme: "darkSystem"
