jenkins:
  controller:
    # List of plugins to be install during Jenkins controller start
    installPlugins:
      - kubernetes:1.27.6
      - workflow-aggregator:2.6
      - configuration-as-code:1.46
      - job-dsl:1.77
      # For GitHub integration
      - blueocean:1.24.3
    sidecars:
      configAutoReload:
        # If enabled: true, Jenkins Configuration as Code will be reloaded on-the-fly without a reboot.  If false or not-specified,
        # jcasc changes will cause a reboot and will only be applied at the subsequent start-up.  Auto-reload uses the
        # http://<jenkins_url>/reload-configuration-as-code endpoint to reapply config when changes to the configScripts are detected.
        enabled: false
    probes:
      livenessProbe:
        initialDelaySeconds: 90

    JCasC:
      configScripts:
        job-definitions: |
          jobs:
            - script: >
                multibranchPipelineJob('api') {
                  description 'Web endpoints and business logic'
                  properties {
                    folderPropertyImpl  {
                      user 'admin'
                      id 'github'
                      domain {
                        name 'blueocean-folder-credential-domain'
                        description 'Blue Ocean Folder Credentials domain'
                      }
                    }
                  }
                  branchSources {
                    branchSource {
                      source {
                        github {
                          id 'blueocean'
                          apiUri 'https://api.github.com'
                          configuredByUrl false
                          credentialsId 'github'
                          repoOwner 'iskprinter'
                          repository 'api'
                          repositoryUrl 'https://github.com/iskprinter/api.git'
                          traits {
                            gitHubBranchDiscovery {
                              strategyId 3
                            }
                            gitHubPullRequestDiscovery {
                              strategyId 1
                            }
                            localBranchTrait
                          }
                        }
                      }
                    }
                  }
                  factory {
                    workflowBranchProjectFactory {
                      scriptPath 'Jenkinsfile'
                    }
                  }
                }
    
  persistence:
    enabled: false
    # volumes:
    #   - name: jenkins-github
    #     secret:
    #       secretName: jenkins-github
    # mounts:
    #   - name: jenkins-github
    #     mountPath: /run/secrets/github_token
    #     subPath: github_token
    #     readOnly: true
